#!/bin/bash

a="Aviation/Command/Mk1BEntente/Mk2Apapt.cfg	
Aviation/Engine/0Mk2LinearAerospike/part.cfg
Aviation/Engine/propEngines/211D.cfg
Aviation/Engine/propEngines/211F.cfg
Aviation/Engine/propEngines/550.cfg	
Aviation/Engine/propEngines/eFan.cfg	
Aviation/Engine/propEngines/J213.cfg
Aviation/Engine/propEngines/Merlin66.cfg
Aviation/Engine/propEngines/NK12M.cfg
Aviation/Engine/propEngines/PT6.cfg
Aviation/Engine/propEngines/R2800.cfg
Aviation/Engine/TinyJet/part.cfg	
Aviation/Hull/fuselage/smalladaptor.cfg	
Aviation/Mk2/SU27adaptor/long.cfg	
Rocketry/Command/MEM/partDescentModule.cfg	
Rocketry/Engine/BlackAdder/Waxwig.cfg	
Rocketry/Engine/size2SRB/part.cfg	
StationsBases/Hull/ServiceMod1/fuelTank.cfg	
StationsBases/Hull/ServiceMod1/smallFuelTank.cfg	
StationsBases/Hull/ServiceMod1/smallServiceModule.cfg	
SuperLaunchers/Engine/K15/partLarge.cfg	
SuperLaunchers/Engine/K15/partMedium.cfg	
SuperLaunchers/Engine/K15/partzNK21.cfg	
SuperLaunchers/Hull/5mQuadAdaptor/size23adapt.cfg	
SuperLaunchers/SaturnV/5mTank0.cfg	
SuperLaunchers/SaturnV/5mTank0NoseCap.cfg	
SuperLaunchers/SaturnV/5mTank1.cfg	
SuperLaunchers/SaturnV/5mTank2.cfg	
SuperLaunchers/SaturnV/5mTank3.cfg	
SuperLaunchers/SaturnV/Stage3Engine.cfg	
SuperLaunchers/Tsar/2-5-3-75.cfg	
SuperLaunchers/Tsar/3-75-5.cfg	
SuperLaunchers/Tsar/5-to-7-25.cfg	"
vi $a
